version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=sreality_scraper_db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - shared-network
    volumes:
      - "./postgres-db:/var/lib/postgresql/data"
  server:
    build:
      dockerfile: "Dockerfile"
      context: "./sreality-scraper-server"
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - postgresql
  ui:
    build:
      dockerfile: "Dockerfile"
      context: "./sreality-scraper-ui"
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      - server
networks:
  shared-network: