import {Pool} from "pg";
import {EstateData} from "./model/estate-data";

const pool = new Pool({
    host: "localhost",
    user: "postgres",
    port: 5432,
    database: "sreality_scraper_db",
    max: 20,
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 2000,
})

export const initDb = async () => {
    await pool.query(`DROP TABLE IF EXISTS "estates"`)
    await pool.query(`
        CREATE TABLE IF NOT EXISTS "estates"
        (
            id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            title VARCHAR(1000),
            img   VARCHAR(1000),
            PRIMARY KEY (id)
        );`)
    console.log("[LOG]: DATABASE HAS BEEN INITIALIZED");
};

export const insertEstates = async (estates: EstateData[]) => {
    const values = estates.map(estateData => `('${estateData.title}','${estateData.img}')`).join(",");
    await pool.query(`
        INSERT INTO "estates" ("title", "img") VALUES ${values};`)
    console.log("[LOG]: DATA HAS BEEN INSERTED INTO THE DATABASE");
};

export const getEstates = async (pageIndex?: number, pageSize?: number) => {
    let baseQuery = `SELECT *
                     FROM "estates"`;
    if (pageIndex && pageSize) {
        baseQuery += ` LIMIT ${pageSize} OFFSET ${pageIndex * pageSize}`;
    }
    const result = await pool.query(baseQuery);
    return result.rows;
};

